//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCalendar.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ColorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ColorResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyCalendar.Resx.ColorResource", typeof(ColorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #CACBCC.
        /// </summary>
        public static string BorderColor {
            get {
                return ResourceManager.GetString("BorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #D6D7D7.
        /// </summary>
        public static string FillColor {
            get {
                return ResourceManager.GetString("FillColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #00aeef.
        /// </summary>
        public static string FOBlue {
            get {
                return ResourceManager.GetString("FOBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #E4E4E4.
        /// </summary>
        public static string GeneralPopupCancelBgColor {
            get {
                return ResourceManager.GetString("GeneralPopupCancelBgColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #00aeef.
        /// </summary>
        public static string GeneralPopupOkayBgColor {
            get {
                return ResourceManager.GetString("GeneralPopupOkayBgColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FFFFFF.
        /// </summary>
        public static string GeneralPopupOkayTextColor {
            get {
                return ResourceManager.GetString("GeneralPopupOkayTextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #EFEFF5.
        /// </summary>
        public static string PageBgColor {
            get {
                return ResourceManager.GetString("PageBgColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #D3D3D3.
        /// </summary>
        public static string SeparatorColor {
            get {
                return ResourceManager.GetString("SeparatorColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #c7c7c7.
        /// </summary>
        public static string SwitchOffColor {
            get {
                return ResourceManager.GetString("SwitchOffColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #C0808080.
        /// </summary>
        public static string TransparentBackgroundColor {
            get {
                return ResourceManager.GetString("TransparentBackgroundColor", resourceCulture);
            }
        }
    }
}
